In [791]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [792]:
df=pd.read_csv('fitness_dataset.csv')

In [793]:
df

age  height_cm  weight_kg  heart_rate  blood_pressure  sleep_hours  \
0      56        152         65        69.6           117.0          NaN   
1      69        186         95        60.8           114.8          7.5   
2      46        192        103        61.4           116.4          NaN   
3      32        189         83        60.2           130.1          7.0   
4      60        175         99        58.1           115.8          8.0   
...   ...        ...        ...         ...             ...          ...   
1995   52        173         98        60.7           106.1          NaN   
1996   61        186         74        51.4           123.8          9.4   
1997   77        198         89        76.7           103.6          8.3   
1998   62        190         63        80.7           115.9          6.7   
1999   51        166         78        89.3           101.8          8.3   

      nutrition_quality  activity_index smokes gender  is_fit  
0                  2.37            3.97     no      F       1  
1                  8.77            3.19      0      F       1  
2                  8.20            2.03      0      F       0  
3                  6.18            3.68      0      M       1  
4                  9.95            4.83    yes      F       1  
...                 ...             ...    ...    ...     ...  
1995               1.54            3.25      1      M       1  
1996               8.63            3.15     no      M       1  
1997               1.98            3.36    yes      M       0  
1998               9.21            2.39      1      F       0  
1999               4.42            1.02      1      M       0  

[2000 rows x 11 columns]

In [794]:
df.shape

(2000, 11)

In [795]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   age                2000 non-null   int64  
 1   height_cm          2000 non-null   int64  
 2   weight_kg          2000 non-null   int64  
 3   heart_rate         2000 non-null   float64
 4   blood_pressure     2000 non-null   float64
 5   sleep_hours        1840 non-null   float64
 6   nutrition_quality  2000 non-null   float64
 7   activity_index     2000 non-null   float64
 8   smokes             2000 non-null   object 
 9   gender             2000 non-null   object 
 10  is_fit             2000 non-null   int64  
dtypes: float64(5), int64(4), object(2)
memory usage: 172.0+ KB


In [796]:
df.describe()

age   height_cm    weight_kg   heart_rate  blood_pressure  \
count  2000.000000  2000.00000  2000.000000  2000.000000     2000.000000   
mean     49.114000   174.53300    83.540500    70.288600      119.908850   
std      17.926564    14.37175    25.852534    11.846339       14.578032   
min      18.000000   150.00000    30.000000    45.000000       90.000000   
25%      34.000000   162.00000    64.000000    62.100000      109.700000   
50%      49.000000   174.00000    83.000000    70.250000      120.000000   
75%      65.000000   187.00000   102.000000    78.425000      129.800000   
max      79.000000   199.00000   250.000000   118.600000      171.200000   

       sleep_hours  nutrition_quality  activity_index       is_fit  
count  1840.000000        2000.000000     2000.000000  2000.000000  
mean      7.513315           5.035140        2.999040     0.399500  
std       1.502031           2.864156        1.136383     0.489918  
min       4.000000           0.000000        1.000000     0.000000  
25%       6.500000           2.547500        2.037500     0.000000  
50%       7.500000           5.065000        2.980000     0.000000  
75%       8.600000           7.470000        3.950000     1.000000  
max      12.000000          10.000000        4.990000     1.000000

In [797]:
df.isnull().sum()

age                    0
height_cm              0
weight_kg              0
heart_rate             0
blood_pressure         0
sleep_hours          160
nutrition_quality      0
activity_index         0
smokes                 0
gender                 0
is_fit                 0
dtype: int64

In [798]:
df['sleep_hours'].mean()

np.float64(7.5133152173913045)

In [799]:
df['sleep_hours'].fillna(df['sleep_hours'].mean(),inplace=True)

In [800]:
df.isnull().sum()

age                  0
height_cm            0
weight_kg            0
heart_rate           0
blood_pressure       0
sleep_hours          0
nutrition_quality    0
activity_index       0
smokes               0
gender               0
is_fit               0
dtype: int64

In [801]:
df.duplicated().sum()

np.int64(0)

In [802]:
df['smokes'].unique()

array(['no', '0', 'yes', '1'], dtype=object)

In [803]:
df['smokes'].replace({'no':0,'yes':1},inplace=True)

In [804]:
df['smokes'].unique()

array([0, '0', 1, '1'], dtype=object)

In [805]:
df['smokes']=df['smokes'].astype(int)

In [806]:
df['smokes'].unique()

array([0, 1])

In [807]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   age                2000 non-null   int64  
 1   height_cm          2000 non-null   int64  
 2   weight_kg          2000 non-null   int64  
 3   heart_rate         2000 non-null   float64
 4   blood_pressure     2000 non-null   float64
 5   sleep_hours        2000 non-null   float64
 6   nutrition_quality  2000 non-null   float64
 7   activity_index     2000 non-null   float64
 8   smokes             2000 non-null   int64  
 9   gender             2000 non-null   object 
 10  is_fit             2000 non-null   int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 172.0+ KB


In [808]:
df['gender'].replace({'F':0,'M':1},inplace=True)

In [809]:
df['gender'] = df['gender'].astype(int)

In [810]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   age                2000 non-null   int64  
 1   height_cm          2000 non-null   int64  
 2   weight_kg          2000 non-null   int64  
 3   heart_rate         2000 non-null   float64
 4   blood_pressure     2000 non-null   float64
 5   sleep_hours        2000 non-null   float64
 6   nutrition_quality  2000 non-null   float64
 7   activity_index     2000 non-null   float64
 8   smokes             2000 non-null   int64  
 9   gender             2000 non-null   int64  
 10  is_fit             2000 non-null   int64  
dtypes: float64(5), int64(6)
memory usage: 172.0 KB


In [811]:
x = df.drop('is_fit',axis=1)
y = df['is_fit']

In [812]:
x

age  height_cm  weight_kg  heart_rate  blood_pressure  sleep_hours  \
0      56        152         65        69.6           117.0     7.513315   
1      69        186         95        60.8           114.8     7.500000   
2      46        192        103        61.4           116.4     7.513315   
3      32        189         83        60.2           130.1     7.000000   
4      60        175         99        58.1           115.8     8.000000   
...   ...        ...        ...         ...             ...          ...   
1995   52        173         98        60.7           106.1     7.513315   
1996   61        186         74        51.4           123.8     9.400000   
1997   77        198         89        76.7           103.6     8.300000   
1998   62        190         63        80.7           115.9     6.700000   
1999   51        166         78        89.3           101.8     8.300000   

      nutrition_quality  activity_index  smokes  gender  
0                  2.37            3.97       0       0  
1                  8.77            3.19       0       0  
2                  8.20            2.03       0       0  
3                  6.18            3.68       0       1  
4                  9.95            4.83       1       0  
...                 ...             ...     ...     ...  
1995               1.54            3.25       1       1  
1996               8.63            3.15       0       1  
1997               1.98            3.36       1       1  
1998               9.21            2.39       1       0  
1999               4.42            1.02       1       1  

[2000 rows x 10 columns]

In [813]:
y

0       1
1       1
2       0
3       1
4       1
       ..
1995    1
1996    1
1997    0
1998    0
1999    0
Name: is_fit, Length: 2000, dtype: int64

In [814]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=12)

In [815]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [816]:
model.fit(x_train,y_train)

SVC(kernel='linear')

In [817]:
y_pred=model.predict(x_test)

In [818]:
from sklearn.metrics import accuracy_score, classification_report, f1_score, confusion_matrix
print('Accuracy Score: ',accuracy_score(y_test,y_pred))
print('F1 Score: ',f1_score(y_test,y_pred))
print('Classification Report:\n',classification_report(y_test,y_pred))
print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred))

Accuracy Score:  0.784
F1 Score:  0.7216494845360825
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.84      0.82       299
           1       0.75      0.70      0.72       201

    accuracy                           0.78       500
   macro avg       0.78      0.77      0.77       500
weighted avg       0.78      0.78      0.78       500

Confusion Matrix:
 [[252  47]
 [ 61 140]]
